---
hero_image: images/banner.png
theme: red
duration: 1
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Paint Box
description: Learn how to make your own paint program.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Making a pencil
- title: Coloured pens
- title: Making mistakes
- title: Changing the pencil width
- title: 'Challenge: Shortcuts'
- title: 'Challenge: More pens'

